/************************************************************************/
/* File Name   : lawinedef.h                                            */
/* Creator     : ax.minaduki@gmail.com                                  */
/* Create Time : March 27th, 2010                                       */
/* Module      : Lawine library                                         */
/* Descript    : Lawine library definition                              */
/************************************************************************/

#ifndef __SD_LAWINE_LAWINEDEF_H__
#define __SD_LAWINE_LAWINEDEF_H__

/************************************************************************/

#include <common.h>

/************************************************************************/

#define L_SCM_VER_UNKNOWN		-1
#define L_SCM_VER_BETA			0
#define L_SCM_VER_STARCRAFT		1
#define L_SCM_VER_HYBRID		2
#define L_SCM_VER_BROODWAR		3

#define L_ERA_ERROR				-1
#define L_ERA_BADLANDS			0
#define L_ERA_PLATFORM			1
#define L_ERA_INSTALL			2
#define L_ERA_ASHWORLD			3
#define L_ERA_JUNGLE			4
#define L_ERA_DESERT			5
#define L_ERA_ICE				6
#define L_ERA_TWILIGHT			7
#define L_ERA_NUM				8

#define L_TILE_SIZE				32

#define L_SPK_WIDTH				640
#define L_SPK_HEIGHT			480

enum {
	L_BRUSH_BADLANDS_DIRT,
	L_BRUSH_BADLANDS_MUD,
	L_BRUSH_BADLANDS_HIGH_DIRT,
	L_BRUSH_BADLANDS_WATER,
	L_BRUSH_BADLANDS_GRASS,
	L_BRUSH_BADLANDS_HIGH_GRASS,
	L_BRUSH_BADLANDS_STRUCTURE,
	L_BRUSH_BADLANDS_ASPHALT,
	L_BRUSH_BADLANDS_ROCKY_GROUND,
	L_BRUSH_BADLANDS_NUM,
};

enum {
	L_BRUSH_PLATFORM_SPACE,
	L_BRUSH_PLATFORM_LOW_PLATFORM,
	L_BRUSH_PLATFORM_RUSTY_PIT,
	L_BRUSH_PLATFORM_PLATFORM,
	L_BRUSH_PLATFORM_DARK_PLATFORM,
	L_BRUSH_PLATFORM_PLATING,
	L_BRUSH_PLATFORM_SOLAR_ARRAY,
	L_BRUSH_PLATFORM_HIGH_PLATFORM,
	L_BRUSH_PLATFORM_HIGH_PLATING,
	L_BRUSH_PLATFORM_ELEVATED_CATWALK,
	L_BRUSH_PLATFORM_NUM,
};

enum {
	L_BRUSH_INSTALL_SUBSTRUCTURE,
	L_BRUSH_INSTALL_FLOOR,
	L_BRUSH_INSTALL_ROOF,
	L_BRUSH_INSTALL_SUBSTRUCTURE_PLATING,
	L_BRUSH_INSTALL_PLATING,
	L_BRUSH_INSTALL_SUBSTRUCTURE_PANELS,
	L_BRUSH_INSTALL_BOTTOMLESS_PIT,
	L_BRUSH_INSTALL_NUM,
};

enum {
	L_BRUSH_ASHWORLD_MAGMA,
	L_BRUSH_ASHWORLD_DIRT,
	L_BRUSH_ASHWORLD_LAVA,
	L_BRUSH_ASHWORLD_SHALE,
	L_BRUSH_ASHWORLD_BROKEN_ROCK,
	L_BRUSH_ASHWORLD_HIGH_DIRT,
	L_BRUSH_ASHWORLD_HIGH_LAVA,
	L_BRUSH_ASHWORLD_HIGH_SHALE,
	L_BRUSH_ASHWORLD_NUM,
};

enum {
	L_BRUSH_JUNGLE_WATER,
	L_BRUSH_JUNGLE_DIRT,
	L_BRUSH_JUNGLE_MUD,
	L_BRUSH_JUNGLE_JUNGLE,
	L_BRUSH_JUNGLE_ROCKY_GROUND,
	L_BRUSH_JUNGLE_RUINS,
	L_BRUSH_JUNGLE_RAISED_JUNGLE,
	L_BRUSH_JUNGLE_TEMPLE,
	L_BRUSH_JUNGLE_HIGH_DIRT,
	L_BRUSH_JUNGLE_HIGH_JUNGLE,
	L_BRUSH_JUNGLE_HIGH_RUINS,
	L_BRUSH_JUNGLE_HIGH_RAISED_JUNGLE,
	L_BRUSH_JUNGLE_HIGH_TEMPLE,
	L_BRUSH_JUNGLE_NUM,
};

enum {
	L_BRUSH_DESERT_TAR,
	L_BRUSH_DESERT_DIRT,
	L_BRUSH_DESERT_DRIED_MUD,
	L_BRUSH_DESERT_SAND_DUNES,
	L_BRUSH_DESERT_ROCKY_GROUND,
	L_BRUSH_DESERT_CRAGS,
	L_BRUSH_DESERT_SANDY_SUNKEN_PIT,
	L_BRUSH_DESERT_COMPOUND,
	L_BRUSH_DESERT_HIGH_DIRT,
	L_BRUSH_DESERT_HIGH_SAND_DUNES,
	L_BRUSH_DESERT_HIGH_CRAGS,
	L_BRUSH_DESERT_HIGH_SANDY_SUNKEN_PIT,
	L_BRUSH_DESERT_HIGH_COMPOUND,
	L_BRUSH_DESERT_NUM,
};

enum {
	L_BRUSH_ICE_ICE,
	L_BRUSH_ICE_SNOW,
	L_BRUSH_ICE_MOGULS,
	L_BRUSH_ICE_DIRT,
	L_BRUSH_ICE_ROCKY_SNOW,
	L_BRUSH_ICE_GRASS,
	L_BRUSH_ICE_WATER,
	L_BRUSH_ICE_OUTPOST,
	L_BRUSH_ICE_HIGH_SNOW,
	L_BRUSH_ICE_HIGH_DIRT,
	L_BRUSH_ICE_HIGH_GRASS,
	L_BRUSH_ICE_HIGH_WATER,
	L_BRUSH_ICE_HIGH_OUTPOST,
	L_BRUSH_ICE_NUM,
};

enum {
	L_BRUSH_TWLIGHT_WATER,
	L_BRUSH_TWLIGHT_DIRT,
	L_BRUSH_TWLIGHT_MUD,
	L_BRUSH_TWLIGHT_CRUSHED_ROCK,
	L_BRUSH_TWLIGHT_CREVICES,
	L_BRUSH_TWLIGHT_FLAGSTONES,
	L_BRUSH_TWLIGHT_SUNKEN_GROUND,
	L_BRUSH_TWLIGHT_BASILICA,
	L_BRUSH_TWLIGHT_HIGH_DIRT,
	L_BRUSH_TWLIGHT_HIGH_CRUSHED_ROCK,
	L_BRUSH_TWLIGHT_HIGH_FLAGSTONES,
	L_BRUSH_TWLIGHT_HIGH_SUNKEN_GROUND,
	L_BRUSH_TWLIGHT_HIGH_BASILICA,
	L_BRUSH_TWLIGHT_NUM,
};

typedef struct {
	WORD mega_index:4;
	WORD group_no:12;
} LTILEIDX;

typedef struct {
	WORD pos:4;
	WORD isom:8;
	WORD unused:4;
} LISOMCOORD;

typedef struct {
	LISOMCOORD left;
	LISOMCOORD top;
	LISOMCOORD right;
	LISOMCOORD bottom;
} LISOMTILE;

typedef struct {
	WORD dd_no;
	WORD x;
	WORD y;
	BYTE owner;
} LDOODAD;

typedef LTILEIDX		*LTILEPTR;
typedef CONST LTILEIDX	*LTILECPTR;

typedef LISOMTILE		*LISOMPTR;
typedef CONST LISOMTILE	*LISOMCPTR;

typedef LDOODAD			*LDDPTR;
typedef CONST LDOODAD	*LDDCPTR;

/************************************************************************/

#endif	/* __SD_CORE_COREDEF_H__ */
